
---
title: "Exercise 6"
author: "Ella Bauer (11927761), Maxi Böck (12466170)"
date: "2023-07-16"
output: html_document
---
```{r}
library(devtools)
```

```{r}
# Funktion 1: clean_text
clean_text <- function(text) {
  # removes special characters
  cleaned_text <- gsub("[[:punct:]]+", "", text)
  # converts into lowercase letters
  cleaned_text <- tolower(cleaned_text)
  # removes digits
  cleaned_text <- gsub("\\b\\d+\\b", "", cleaned_text)
  # remove extra spaces
  cleaned_text <- gsub("\\s+", " ", cleaned_text)
  # remove spaces in front and at end
  cleaned_text <- trimws(cleaned_text)
  # return cleaned text
  return(cleaned_text)
  
}
```



```{r}
# Funktion 2: remove_stopwords
remove_stopwords <- function(text) {
  # Definiere eine Liste von Stoppwörtern
  stopwords <- c("the", "and", "is", "a", "of", "in", "to", "it", "der", "die", "das", "und", "ist", "ein", "von", "in", "zu", "es", "Es", "Zu", "Und", "Ist", "Ein", "Von", "In", "Der", "Die", "Das")
  
  # Ersetze alle Leerzeichen vor und nach einem Komma durch ein einzelnes Leerzeichen
  text <- gsub("\\s*,\\s*", ",", text)
  
  # Teile den Text in einzelne Wörter auf
  words <- strsplit(text, "\\s+")
  
  # Entferne Stoppwörter
  filtered_words <- words[[1]][!tolower(words[[1]]) %in% tolower(stopwords)]
  
  # Verbinde die verbleibenden Wörter wieder zu einem Text
  filtered_text <- paste(filtered_words, collapse = " ")
  
  # Rückgabe des bereinigten Texts
  return(filtered_text)
}

```


```{r}
# function 3: counting words
count_words <- function(text) {
  words <- strsplit(text, "\\s+")[[1]]  # Split the text into individual words
  num_words <- length(words)  #Count the number of words
  return(num_words)
}
```
